services:
  - type: web
    name: asistente-fisica
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_PERSIST_DIR
        value: ./rag/index/chroma
      - key: HF_HOME
        value: ./rag/index/hf-model
      - key: SENTENCE_TRANSFORMERS_HOME
        value: ./rag/index/hf-model
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
